#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
# BSPWMRC | Hacker environment                                             
# Color theme: FBI

# xprop | grep WM_CLASS

wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d I II III IV V VI

xsetroot -cursor_name left_ptr &

bspc config border_width         1
bspc config focused_border_color \#edefec
bspc config normal_border_color \#7d8b94
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config gapless_monocle true
bspc config paddingless_monocle true

#cor preselection bspwm pra abrir janela nova
#roxo = bspc config presel_feedback_color '#512da8'
#bspc config presel_feedback_color '#2d52a8'


#bspc rule -a 'Gnome-terminal' state=floating rectangle=1000x600+150+150 center=true
#bspc rule -a 'Google-chrome' desktop='I'
#bspc rule -a 'firefox' desktop='I'
bspc rule -a 'SimpleScreenRecorder' state=floating follow=on
bspc rule -a 'BleachBit' state=floating follow=on
bspc rule -a 'stacer' state=floating follow=on
bspc rule -a 'org.gnome.Nautilus' state=floating follow=on
bspc rule -a 'gnome-calculator' state=floating follow=on
bspc rule -a 'Nitrogen' state=floating follow=on
bspc rule -a 'Synaptic' state=floating follow=on


# KeyBoard
#setxkbmap -model abnt2 -layout br -variant abnt2
setxkbmap us
# Wallpaper
# NSA
#feh --bg-fill ~/Wallpapers/35415.jpg &

# Pentest
#feh --bg-fill ~/Wallpapers/mr-robot-elliot.jpeg &

#kali linux black
#feh --bg-fill ~/Wallpapers/35404.jpg &

#DOD
#feh --bg-fill ~/Wallpapers/DOD.jpg &

# Numlock ativo
/usr/bin/numlockx

#WAL que da cor ao terminal e letras
wal -R

#time
timedatectl set-timezone America/Sao_Paulo


# Auto-Start

picom &
${HOME}/.config/polybar/launch.sh --cuts &
${HOME}/.scripts/wall-scripts/fbi_wal.sh &
